version: '3.7'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            POSTGRES_DB: 'db'
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'admin123'
        networks:
            - internal
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_DB: 'db'
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'admin123'
        networks:
            - internal
        working_dir: /postgres-data
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:

networks:
    internal:
        driver: bridge
