version: "3"

services:
    db:
        build:
            context: ./database
            dockerfile: Dockerfile
        restart: always
        env_file:
            - database/.env
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - ./database/:/bot/
        networks:
            - internal

    tests:
        build:
            context: .
            dockerfile: ./test/Dockerfile
        env_file:
            - database/.env
        command: 'python3 -m unittest test/db_test.py'
        networks:
            - internal
        depends_on:
            - db

    bot:
        build:
            context: .
            dockerfile: ./bot/Dockerfile
        restart: always
        env_file:
            - database/.env
            - bot/.env
        command: 'python3 bot/bot.py'
        networks:
            - internal
        depends_on:
            - db
            - tests

networks:
    internal:
        driver: bridge