{
 "title": "telegram-smg-gazpromcps",
 "description": "Daily activity tracker. Gazpromcps bot. SMG",
 "tags": [
  "telegram",
  "bot",
  "smg"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "logs # full",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"telegram-smg-logs\"}"
    }
   ]
  },
  {
   "title": "logs # level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max(count_over_time({job=\"telegram-smg-logs\"}[30m])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "logs # count # info",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({level=\"INFO\"}[1h])) by (level)",
     "legendFormat": "INFO"
    }
   ]
  },
  {
   "title": "logs # count # warn",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({level=\"WARN\"}[1h])) by (level)",
     "legendFormat": "WARN"
    }
   ]
  },
  {
   "title": "logs # count # error",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({level=\"ERROR\"}[1h])) by (level)",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "logs # by level # pie chart",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({job=\"telegram-smg-logs\"} [1h]))",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "users # by role",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (role) (count by(role, uid) (rate({job=\"telegram-smg-logs\"} | regexp `.*uid=(?P<uid>.*),.*role=(?P<role>.*).*` [$__range])))",
     "legendFormat": "{{ role }}"
    }
   ]
  },
  {
   "title": "users # count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(uid) (sum by(uid) (rate({job=\"telegram-smg-logs\"} | regexp `.*uid=(?P<uid>.*),.*role=(?P<role>.*).*` [$__range]))))",
     "legendFormat": "USERS"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total amount of logs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/smg-bot.log\"} [$__range]))"
    }
   ]
  }
 ]
}